// 多言語対応データ
export const LANG_DATA = {
  ja: {
    greeting: "こんにちは",
    login: "ログイン",
    logout: "ログアウト",
    school_id: "学校ID",
    school_id_placeholder: "学校ID",
    login_button: "ログイン",
    login_id_hint: "学校IDは、pL:2^4,5,101 のような形式の文字列です。",
    copyright: "(c) 2022-2025 Carnation Studio v0.0.2",
    menu_toaster: "ToasterMachine",
    menu_scr: "SCR",
    menu_setting: "設定",
    menu_pickramu: "Pickramu",
    ask_placeholder: "ここに質問を入力",
    send: "送信",
    new_chat: "新規チャット",
    chat_placeholder: "メッセージを入力",
    search: "検索",
    search_keyword: "キーワード検索",
    search_placeholder: "キーワードを入力",
    post: "ポストする",
    post_title: "タイトル",
    post_content: "内容",
    post_content_placeholder: "内容を入力",
    back: "←",
    estore: "eStore",
    math_kit: "Math Kit",
    room: "Room",
    pickramu_work: "Pickramu ワーク",
    pickramu_tab: "教材ワーク",
    eguide_tab: "eGuide",
    select_material: "教材選択：",
    load: "読み込み",
    error_occurred: "エラーが発生しました。",
    api_error_429: "APIの呼び出し回数が制限を超えました。しばらく待ってから再度お試しください。",
    api_error_401: "APIキーが無効です。正しいAPIキーを設定してください。",
    api_error_400: "リクエストが不正です。入力内容を確認してください。",
    api_error_fetch: "APIとの通信に失敗しました。インターネット接続を確認してください。",
    api_error_invalid_response: "APIからの応答形式が不正でした。もう一度お試しください。",
    clear_chat_confirm: "チャットをクリアしますか？",
    post_success: "投稿が完了しました。",
    post_fail: "投稿に失敗しました。",
    next: "次へ",
    prev: "前へ",
    introduction: "導入",
    main: "本題",
    examples: "具体例",
    exercises: "演習",
    summary: "まとめ",
    next_preview: "次回予告",
    question: "質問",
    answer: "回答",
    question_fail: "申し訳ありません。回答の生成に失敗しました。もう一度お試しください。"
  },
  en: {
    greeting: "Hello",
    login: "Login",
    logout: "Logout",
    school_id: "School ID",
    school_id_placeholder: "School ID",
    login_button: "Login",
    login_id_hint: "School ID is a string like pL:2^4,5,101.",
    copyright: "(c) 2022-2025 Carnation Studio v0.0.2",
    menu_toaster: "ToasterMachine",
    menu_scr: "SCR",
    menu_setting: "Settings",
    menu_pickramu: "Pickramu",
    ask_placeholder: "Enter your question here",
    send: "Send",
    new_chat: "New Chat",
    chat_placeholder: "Enter your message",
    search: "Search",
    search_keyword: "Keyword Search",
    search_placeholder: "Enter keyword",
    post: "Post",
    post_title: "Title",
    post_content: "Content",
    post_content_placeholder: "Enter content",
    back: "←",
    estore: "eStore",
    math_kit: "Math Kit",
    room: "Room",
    pickramu_work: "Pickramu Work",
    pickramu_tab: "Material Work",
    eguide_tab: "eGuide",
    select_material: "Select Material:",
    load: "Load",
    error_occurred: "An error occurred.",
    api_error_429: "API call limit exceeded. Please try again later.",
    api_error_401: "Invalid API key. Please set a valid API key.",
    api_error_400: "Bad request. Please check your input.",
    api_error_fetch: "Failed to communicate with API. Please check your internet connection.",
    api_error_invalid_response: "Invalid API response format. Please try again.",
    clear_chat_confirm: "Clear chat?",
    post_success: "Post successful.",
    post_fail: "Failed to post.",
    next: "Next",
    prev: "Previous",
    introduction: "Introduction",
    main: "Main",
    examples: "Examples",
    exercises: "Exercises",
    summary: "Summary",
    next_preview: "Next Preview",
    question: "Question",
    answer: "Answer",
    question_fail: "Sorry, failed to generate answer. Please try again."
  },
  // 他の言語も追加可能
};

import { CURRENT_LANG } from './config.js';
/**
 * 指定したキーの文言を現在の言語で取得
 * @param {string} key
 * @param {string} lang - 省略時はconfig.jsのCURRENT_LANG
 */
export function t(key, lang = CURRENT_LANG) {
  return (LANG_DATA[lang] && LANG_DATA[lang][key]) || key;
} 