// 多言語対応データ
export const LANG_DATA = {
  ja: {
    greeting: "こんにちは",
    login: "ログイン",
    logout: "ログアウト",
    school_id: "学校ID",
    school_id_placeholder: "学校ID",
    login_button: "ログイン",
    login_id_hint: "学校IDは、pL:2^4,5,101 のような形式の文字列です。",
    copyright: "(c) 2022-2025 Carnation Studio v0.0.2",
    menu_toaster: "ToasterMachine",
    menu_scr: "SCR",
    menu_setting: "設定",
    menu_pickramu: "Pickramu",
    ask_placeholder: "ここに質問を入力",
    send: "送信",
    new_chat: "新規チャット",
    chat_placeholder: "メッセージを入力",
    search: "検索",
    search_keyword: "キーワード検索",
    search_placeholder: "キーワードを入力",
    post: "ポストする",
    post_title: "タイトル",
    post_content: "内容",
    post_content_placeholder: "内容を入力",
    back: "←",
    estore: "eStore",
    math_kit: "Math Kit",
    room: "Room",
    pickramu_work: "Pickramu ワーク",
    pickramu_tab: "教材ワーク",
    eguide_tab: "eGuide",
    select_material: "教材選択：",
    load: "読み込み",
    error_occurred: "エラーが発生しました。",
    api_error_429: "APIの呼び出し回数が制限を超えました。しばらく待ってから再度お試しください。",
    api_error_401: "APIキーが無効です。正しいAPIキーを設定してください。",
    api_error_400: "リクエストが不正です。入力内容を確認してください。",
    api_error_fetch: "APIとの通信に失敗しました。インターネット接続を確認してください。",
    api_error_invalid_response: "APIからの応答形式が不正でした。もう一度お試しください。",
    clear_chat_confirm: "チャットをクリアしますか？",
    post_success: "投稿が完了しました。",
    post_fail: "投稿に失敗しました。",
    next: "次へ",
    prev: "前へ",
    introduction: "導入",
    main: "本題",
    examples: "具体例",
    exercises: "演習",
    summary: "まとめ",
    next_preview: "次回予告",
    question: "質問",
    answer: "回答",
    question_fail: "申し訳ありません。回答の生成に失敗しました。もう一度お試しください。"
  },
  en: {
    greeting: "Hello",
    login: "Login",
    logout: "Logout",
    school_id: "School ID",
    school_id_placeholder: "School ID",
    login_button: "Login",
    login_id_hint: "School ID is a string like pL:2^4,5,101.",
    copyright: "(c) 2022-2025 Carnation Studio v0.0.2",
    menu_toaster: "ToasterMachine",
    menu_scr: "SCR",
    menu_setting: "Settings",
    menu_pickramu: "Pickramu",
    ask_placeholder: "Enter your question here",
    send: "Send",
    new_chat: "New Chat",
    chat_placeholder: "Enter your message",
    search: "Search",
    search_keyword: "Keyword Search",
    search_placeholder: "Enter keyword",
    post: "Post",
    post_title: "Title",
    post_content: "Content",
    post_content_placeholder: "Enter content",
    back: "←",
    estore: "eStore",
    math_kit: "Math Kit",
    room: "Room",
    pickramu_work: "Pickramu Work",
    pickramu_tab: "Material Work",
    eguide_tab: "eGuide",
    select_material: "Select Material:",
    load: "Load",
    error_occurred: "An error occurred.",
    api_error_429: "API call limit exceeded. Please try again later.",
    api_error_401: "Invalid API key. Please set a valid API key.",
    api_error_400: "Bad request. Please check your input.",
    api_error_fetch: "Failed to communicate with API. Please check your internet connection.",
    api_error_invalid_response: "Invalid API response format. Please try again.",
    clear_chat_confirm: "Clear chat?",
    post_success: "Post successful.",
    post_fail: "Failed to post.",
    next: "Next",
    prev: "Previous",
    introduction: "Introduction",
    main: "Main",
    examples: "Examples",
    exercises: "Exercises",
    summary: "Summary",
    next_preview: "Next Preview",
    question: "Question",
    answer: "Answer",
    question_fail: "Sorry, failed to generate answer. Please try again."
  },
  ko: {
    greeting: "안녕하세요",
    login: "로그인",
    logout: "로그아웃",
    school_id: "학교 ID",
    school_id_placeholder: "학교 ID",
    login_button: "로그인",
    login_id_hint: "학교 ID는 pL:2^4,5,101과 같은 형식의 문자열입니다.",
    copyright: "(c) 2022-2025 Carnation Studio v0.0.2",
    menu_toaster: "토스터머신",
    menu_scr: "SCR",
    menu_setting: "설정",
    menu_pickramu: "Pickramu",
    ask_placeholder: "여기에 질문을 입력하세요",
    send: "보내기",
    new_chat: "새 채팅",
    chat_placeholder: "메시지를 입력하세요",
    search: "검색",
    search_keyword: "키워드 검색",
    search_placeholder: "키워드를 입력하세요",
    post: "게시하기",
    post_title: "제목",
    post_content: "내용",
    post_content_placeholder: "내용을 입력하세요",
    back: "←",
    estore: "eStore",
    math_kit: "Math Kit",
    room: "Room",
    pickramu_work: "Pickramu 워크",
    pickramu_tab: "교재 워크",
    eguide_tab: "eGuide",
    select_material: "교재 선택:",
    load: "불러오기",
    error_occurred: "오류가 발생했습니다.",
    api_error_429: "API 호출 횟수가 제한을 초과했습니다. 잠시 후 다시 시도해 주세요.",
    api_error_401: "API 키가 유효하지 않습니다. 올바른 API 키를 설정해 주세요.",
    api_error_400: "잘못된 요청입니다. 입력 내용을 확인해 주세요.",
    api_error_fetch: "API와의 통신에 실패했습니다. 인터넷 연결을 확인해 주세요.",
    api_error_invalid_response: "API 응답 형식이 잘못되었습니다. 다시 시도해 주세요.",
    clear_chat_confirm: "채팅을 지우시겠습니까?",
    post_success: "게시가 완료되었습니다.",
    post_fail: "게시 실패.",
    next: "다음",
    prev: "이전",
    introduction: "도입",
    main: "본론",
    examples: "예시",
    exercises: "연습문제",
    summary: "요약",
    next_preview: "다음 예고",
    question: "질문",
    answer: "답변",
    question_fail: "죄송합니다. 답변 생성에 실패했습니다. 다시 시도해 주세요."
  },
  zh: {
    greeting: "你好",
    login: "登录",
    logout: "登出",
    school_id: "学校ID",
    school_id_placeholder: "学校ID",
    login_button: "登录",
    login_id_hint: "学校ID是类似于pL:2^4,5,101的字符串。",
    copyright: "(c) 2022-2025 Carnation Studio v0.0.2",
    menu_toaster: "ToasterMachine",
    menu_scr: "SCR",
    menu_setting: "设置",
    menu_pickramu: "Pickramu",
    ask_placeholder: "请输入您的问题",
    send: "发送",
    new_chat: "新聊天",
    chat_placeholder: "请输入消息",
    search: "搜索",
    search_keyword: "关键词搜索",
    search_placeholder: "请输入关键词",
    post: "发布",
    post_title: "标题",
    post_content: "内容",
    post_content_placeholder: "请输入内容",
    back: "←",
    estore: "eStore",
    math_kit: "Math Kit",
    room: "Room",
    pickramu_work: "Pickramu 作业",
    pickramu_tab: "教材作业",
    eguide_tab: "eGuide",
    select_material: "教材选择：",
    load: "加载",
    error_occurred: "发生错误。",
    api_error_429: "API调用次数已超限，请稍后再试。",
    api_error_401: "API密钥无效。请设置正确的API密钥。",
    api_error_400: "请求无效。请检查您的输入。",
    api_error_fetch: "与API通信失败。请检查您的网络连接。",
    api_error_invalid_response: "API响应格式无效。请重试。",
    clear_chat_confirm: "要清除聊天记录吗？",
    post_success: "发布成功。",
    post_fail: "发布失败。",
    next: "下一步",
    prev: "上一步",
    introduction: "导入",
    main: "本题",
    examples: "例子",
    exercises: "练习题",
    summary: "总结",
    next_preview: "下次预告",
    question: "问题",
    answer: "回答",
    question_fail: "很抱歉，生成回答失败。请重试。"
  }
};

import { CURRENT_LANG } from './config.js';
/**
 * 指定したキーの文言を現在の言語で取得
 * @param {string} key
 * @param {string} lang - 省略時はconfig.jsのCURRENT_LANG
 */
export function t(key, lang = CURRENT_LANG) {
  return (LANG_DATA[lang] && LANG_DATA[lang][key]) || key;
} 