service: deep-school-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1 # 東京リージョンなど任意

functions:
  api:
    handler: src/lambda.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: '{proxy+}'
          method: any

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  individually: true